### ISSUE TITLE
The "lea" instruction is not disassembled correctly

### ISSUE THREAD

**Issue by alexvillalb159** [Mithreindeir/libdisas#1]
Hello friend!: Thank you for your code. The "lea" instruction is not disassembled correctly. I was reviewing the code and it's a matter of modifying line 174 of the file /src/arch/x86/x86.ins, instead of
"8d lea Gv", modify by "8d lea Gv Av". That is, it was only necessary to place the letters that identify the memory operators: Av. 
Enough with that to decode the machine code well in 32 and 64 bits, so I guess it was just a little oversight.

**Comment by Mithreindeir** [comment]
@alexvillalb159  Hi friend! Good work finding that, I didn't think anyone had used my code, and it is very poorly documented so that is pretty impressive. I probably made an error typing it, as I typed all of those files by hand if u can believe that. If I remember correctly, lea uses modrm encoding only such that the mod bits must not be 3, (meaning it must not be a register, only a memory address). A is used for direct addresses, mostly like call instructions. Thank you!

**Comment by alexvillalb159** [comment]
I used it. I link it to a program that uses the ptrace system call to debug "on the fly", for reasons of curiosity and research. Link with gdb I saw it much more tedious, in terms of researching and reading the code, in addition the compilation of your code is much simpler and it was just what I was looking for. I don't like having a lot of redundant code.
As for the "lea" instruction, what seems curious to me is that when it is compiled in 64 bits, the SIB byte is added (your code recognizes it), in the intel documentation that is not very well clarified, it is not something that is infer directly from reading the "lea" instruction in the reference manual. For me it was a surprise, I still don't see that clearly specified in the documentation, I had to infer it. Clearly your mistake was a typing problem.
